### ISSUE TITLE
Create Application with Logger

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnackNew#2]
### Background
Logging and debugging is very important to keep the application bug-free and to fix issues without complications. 

### Tasks
- [ ] Add Log4j 2 to Maven dependencies
- [ ] Create Log4j 2 configuration file to create console output and daily rolling log files
- [ ] Create a dedicated class as application entry point
- [ ] Implement option to set the log level via console argument
