### ISSUE TITLE
Prepare Super Smash Bros. Melee Plugin

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnackNew#4]
### Background
The application was originally made for a SSBM tournament, so we need this plugin first.

### Tasks
- [ ] Create character information files
- [ ] Create character assets
- [ ] Create plugin information file
